#!/usr/bin/env python3
"""Build the approved Well and Good Growth website for production."""
from pathlib import Path
from html import escape
from hashlib import sha256
import shutil
import json
import re
import sys
from urllib.parse import urlencode

sys.path.insert(0, str(Path(__file__).resolve().parent))
import growth_art as art  # noqa: E402  shared bridge geometry, ship symbol, logo mark, grain
import art_showpieces as showpieces  # noqa: E402,F401  homepage hero bridge, service drawings, automation lock, 404, thank-you
import art_local as local  # noqa: E402,F401  boat journey, canal map, results columns

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'site-growth'
MOTION = DESIGN / 'motion'
OUTPUT = ROOT / 'public'
SOCIAL_IMAGE = 'https://www.wellandgoodgrowth.ca/assets/well-and-good-growth-social-20260925.png'


def bundle(name):
    """style.css or site.js plus the motion partials of the same type, in name order.

    Each script partial is wrapped so an error in one piece is logged without
    stopping the others (partials are IIFEs and share nothing but window.WG).
    """
    base = DESIGN / name
    parts = [base] + sorted(MOTION.glob('*' + base.suffix))
    chunks = []
    for part in parts:
        label = part.relative_to(DESIGN).as_posix()
        text = part.read_text().rstrip() + '\n'
        if base.suffix == '.js':
            text = f'try {{\n{text}}} catch (error) {{ console.error("{label}", error); }}\n'
        chunks.append(f'/* ---- {label} ---- */\n{text}')
    return '\n'.join(chunks)


BUNDLES = {name: bundle(name) for name in ('style.css', 'site.js')}
# Content-addressed assets keep returning visitors on the matching stylesheet and script.
ASSETS = {name: f'{Path(name).stem}.{sha256(BUNDLES[name].encode()).hexdigest()[:12]}{Path(name).suffix}' for name in BUNDLES}
BRAND = f'<a class="brand" href="/">{art.HEADER_MARK}<span class="brand-name">Well <em>and</em> Good Growth</span></a>'
# The canal reading bar (motion piece 5): a water line along the top edge with the freighter riding it.
CANAL_BAR = (f'<div class="canal-bar" aria-hidden="true"><span class="canal-track"></span><span class="canal-fill"></span>'
             f'<svg class="canal-ship" viewBox="{art.SHIP_VB}" focusable="false"><use href="#ship" x="-36" y="-24" width="72" height="34"/></svg></div>')


def cta(label='Let’s talk', service='Help me choose'):
    return f'<button class="button" type="button" data-contact="{escape(service)}">{label}<span aria-hidden="true">↗</span></button>'


def faq(items):
    return '<section class="container section faq"><h2>A few practical questions.</h2><div>' + ''.join(
        f'<details><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>' for question, answer in items) + '</div></section>'


def contact(title='Let’s take something<br>off your plate.', body='Share the task you want to automate or the website and marketing you need. You’ll get a personal reply from Matt to discuss a practical starting point.', label='Discuss your project', service='Help me choose'):
    return f'<section class="contact-section container section" id="contact"><h2>{title}</h2><p>{body}</p>{cta(label, service)}</section>'


def pricing():
    plans = [
        ('Launch', '199', '$750 setup', '$1,990', 'A one-page website with local search essentials.', [
            'One-page website with mobile tap-to-call', 'Google Business Profile, local SEO, AI search foundations and citations', 'Hosting, SSL, backups and monitoring', '4 social posts per month on 1 platform']),
        ('Grow', '699', '$1,500 onboarding', '$6,990', 'A fuller website with regular content and marketing.', [
            'Everything in Launch', 'Standard website with booking or quote flow', 'Active local SEO and 2 content pages per month', 'Social on 2 platforms, around 12 posts per month', 'Review management and a monthly report']),
        ('Dominate', '1,299', '$2,500 onboarding', '$12,990', 'More content and channels, with monthly strategy.', [
            'Everything in Grow', 'Premium website, positioning and messaging', 'SEO and AI search work, 4 content pieces per month', 'Social on 3 to 4 platforms and weekly video', 'Monthly strategy call and reporting dashboard']),
    ]
    cards = ''.join(f'''<article class="plan"><h3>{name}</h3><p class="plan-description">{description}</p><p class="price">${amount}<span>/month</span></p><p class="plan-terms">Plus {setup}<br>Annual plan: {annual}</p><ul>{''.join(f'<li>{item}</li>' for item in items)}</ul>{cta('Discuss ' + name,name)}</article>''' for name,amount,setup,annual,description,items in plans)
    return f'''<section class="pricing-section section" id="plans"><div class="container"><h2>Choose the support<br>you need each month.</h2><p class="section-intro">Each package combines a website with ongoing marketing. Compare the pages, content, and channels included, then talk with me about which fits your business.</p><div class="plans">{cards}</div><p class="pricing-note">All prices in CAD. Ad budget billed separately. Monthly plans can be cancelled anytime. AI automation is bespoke and scoped separately.</p></div></section>'''


def project():
    return '''<section class="portfolio-section container section" id="work"><h2>See the work<br>for yourself.</h2><div class="portfolio-grid"><article class="portfolio-feature"><a class="portfolio-image" href="/frank-baggetta/" aria-label="Read the Frank Baggetta case study"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" loading="lazy" alt="Frank Baggetta’s updated website: The Accordion Player Who Gets Toronto Dancing."></a><div class="portfolio-caption"><div><p>Completed client website</p><h3>Frank Baggetta</h3></div><a class="text-link" href="/frank-baggetta/">Read case study ↗</a></div><p class="small-note">Frank reported three new enquiries in the first month after the original launch.</p></article><article class="portfolio-feature"><a class="portfolio-image" href="https://wellandvotes.ca/" aria-label="Visit the Welland Votes election guide"><img src="/assets/wellandvotes-preview-20260914.webp" width="1268" height="1818" loading="lazy" alt="Welland Votes election guide, with candidate comparisons and an interactive ward map."></a><div class="portfolio-caption"><div><p>Live community project</p><h3>Welland Votes</h3></div><a class="text-link" href="https://wellandvotes.ca/">Visit website ↗</a></div><p class="small-note">An independent election guide with candidate comparisons, sourced profiles, and an interactive ward map.</p></article><article><a class="portfolio-image" href="/work/evelyns/" aria-label="View Evelyn’s Sandwich Factory concept website"><img src="/assets/evelyns-preview.webp" width="1000" height="729" loading="lazy" alt="Evelyn’s Sandwich Factory concept website, with menu and ordering information."></a><div class="portfolio-caption"><div><p>Concept build</p><h3>Evelyn’s Sandwich Factory</h3></div><a class="text-link" href="/work/evelyns/">View concept ↗</a></div></article><article><a class="portfolio-image" href="/work/jk-motors/" aria-label="View the JK Motors concept website"><img src="/assets/jk-motors-preview.webp" width="1000" height="729" loading="lazy" alt="JK Motors concept website, with repair services and a call-first layout."></a><div class="portfolio-caption"><div><p>Concept build</p><h3>JK Motors</h3></div><a class="text-link" href="/work/jk-motors/">View concept ↗</a></div></article></div><p class="small-note">Evelyn’s and JK Motors are concept builds, not commissioned client websites.</p></section>'''


def founder():
    return '''<section class="founder-section container section" id="about"><div class="founder-photo"><img src="/assets/matt-headshot.webp" width="600" height="600" loading="lazy" alt="Matthew Baggetta."></div><div><h2>You work<br>directly with Matt.</h2><p>I’m Matt, based in Welland. For over a decade, I’ve run content and growth marketing for tech startups around the world. Now I bring that experience to businesses across Niagara and the GTA.</p><p>I write the copy, build the website, and connect the tools. You can talk to the person doing the work, explain what’s getting in the way, and see how it’s being addressed.</p><p>We start with the part your business needs most. That might be a website that explains your services, content that answers customer questions, or an automation for a task you’re tired of repeating.</p>''' + cta('Talk with Matt') + '</div></section>'

def page(title, description, body, active=''):
    links = [('automation','AI automation','/services/automation/'),('websites','Websites','/services/websites/'),('growth','Growth marketing','/services/growth/')]
    current_service = {'websites':'Web development','growth':'Growth marketing','automation':'AI automation'}.get(active,'Help me choose')
    body = body.replace('data-contact="Help me choose"', f'data-contact="{current_service}"')
    nav = ''.join(f'<a href="{url}"' + (' aria-current="page"' if key == active else '') + f'>{label}</a>' for key,label,url in links)
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="index,follow"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="icon" href="/assets/favicon-32.png" sizes="32x32" type="image/png"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><title>{escape(title)} | Well and Good Growth</title><meta name="description" content="{escape(description)}"><link rel="preload" href="/fonts/libre-franklin.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/fonts/besley.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/{ASSETS['style.css']}"><script defer src="/{ASSETS['site.js']}"></script></head>
<body>{art.SPRITE}<a href="#main" class="skip-link">Skip to content</a>{CANAL_BAR}<header class="site-header"><div class="site-header-inner container">{BRAND}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menu</button><nav class="main-nav" id="main-nav" aria-label="Main navigation">{nav}<a href="/#about">Meet Matt</a>{cta(service=current_service)}</nav></div></header><main id="main">{body}</main><footer class="container">{BRAND}<div><span>Matthew Baggetta · Welland, Ontario</span><a href="/website-design-niagara/">Website design Niagara</a><a href="/website-design-welland/">Website design Welland</a><a href="/website-design-st-catharines/">Website design St. Catharines</a><a href="/niagara-seo/">Niagara SEO</a><a href="/privacy/">Privacy</a><a href="mailto:matt@wellandgoodwebsites.ca">Email Matt</a></div></footer>
<dialog class="contact-preview" aria-labelledby="contact-title"><button class="dialog-close" type="button">Close</button><h2 id="contact-title">Tell me what you need a hand with.</h2><p id="contact-intro" aria-live="polite">Choose a service, or leave it on “Help me choose.” I’ll read your enquiry and reply personally.</p><form class="enquiry-form" action="https://formsubmit.co/835081ce825a6a057837907299436066" method="post" data-page-service="{current_service}"><input type="hidden" name="_subject" value="Well and Good Growth: service enquiry"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="false"><input type="hidden" name="_next" value="https://www.wellandgoodgrowth.ca/thank-you/"><input type="text" name="_honey" class="honeypot" tabindex="-1" autocomplete="off" aria-hidden="true"><label>What would you like help with?<select name="service"><option value="Help me choose">Help me choose</option><option value="Web development">Web development</option><option value="Growth marketing">Growth marketing</option><option value="AI automation">AI automation</option></select></label><label id="package-field" hidden>Package you’re considering (optional)<select name="package" disabled><option value="">Help me choose</option><option>Launch</option><option>Grow</option><option>Dominate</option><option>Custom project</option></select></label><p class="service-form-note" id="automation-form-note" hidden>The build, software costs, and support are quoted before paid work begins.</p><label>Business name or website (optional)<input name="business" autocomplete="off"></label><label><span id="message-label">What would you like to improve?</span><textarea name="message" required placeholder="What does your business do, and what would you like to change or take off your plate?"></textarea></label><div class="contact-details"><label>Your name<input name="name" autocomplete="name" required></label><label>Email address<input name="email" type="email" autocomplete="email" required></label></div><button class="button" type="submit">Send enquiry <span aria-hidden="true">↗</span></button><p class="form-privacy">Your details are sent through FormSubmit for email delivery and used to respond to your enquiry. <a href="/privacy/">Privacy notice</a>.</p></form><p class="form-result" role="status"></p></dialog></body></html>'''
    # Link fallback allows enquiries with scripts disabled or opening a new tab.
    def contact_link(match):
        attrs, label = match.groups()
        selection = re.search(r'data-contact="([^"]+)"', attrs).group(1)
        is_package = selection in {'Launch', 'Grow', 'Dominate'}
        query = {'service': current_service if is_package else selection}
        if is_package:
            query['package'] = selection
        attrs = attrs.replace(' type="button"', '')
        return f'<a {attrs} href="/contact/?{escape(urlencode(query))}">{label}</a>'
    return re.sub(r'<button ([^>]*data-contact="[^"]+"[^>]*)>(.*?)</button>', contact_link, html)


home = '''<section class="business-hero"><div class="container"><div class="business-hero-copy"><h1>Running your business shouldn’t mean <em>doing everything yourself.</em></h1><p class="hero-description">Free up your time with AI automation, and turn more interest into enquiries with a website and marketing built around your customers. Put a decade of marketing experience and today’s technology to work for your business.</p><div class="hero-actions">''' + cta('Request a free website preview') + ' ' + cta('Discuss your project') + '''<a class="text-link" href="#services">Choose a service ↗</a></div><p class="small-note">Based in Welland. Serving Niagara and the GTA.</p></div><div class="hero-emblem hero-motion" data-hero-motion><div class="motion-view"><img class="motion-poster" src="/assets/bridge-magic-clean-edge.webp" alt="Well and Good bridge emblem" width="600" height="600" fetchpriority="high"><video class="motion-video" muted playsinline preload="none" aria-hidden="true" tabindex="-1"><source data-src="/assets/bridge-magic-clean-edge.mp4" type="video/mp4"></video></div><noscript><style>.hero-motion .motion-poster{visibility:visible}</style></noscript></div></div></section>
<section class="services-section container section" id="services"><h2>Start with the work you need a hand with.</h2><div class="service-links"><a href="/services/automation/"><h3>AI automation</h3><p>Spend less of your day researching prospects, preparing updates, and moving information between tools. Put those repeatable steps into an AI workflow built around your business.</p><span class="service-link-label">Explore AI automation ↗</span></a><a href="/services/websites/"><h3>Web development</h3><p>Give customers a reason to choose you with clear messaging, thoughtful design, and an easy path to enquire. Get the strategy and technical expertise to make your website work for your business.</p><span class="service-link-label">Websites &amp; packages ↗</span></a><a href="/services/growth/"><h3>Growth marketing</h3><p>Help customers find your business and take the next step. Put a clear strategy behind your search, content, and campaigns: who to reach, what to say, and how to measure progress.</p><span class="service-link-label">Growth &amp; packages ↗</span></a></div><p class="small-note"><a class="text-link" href="/services/automation/#builds">See an interview workflow ↗</a></p></section>''' + founder() + project() + contact()

websites = '''<section class="service-hero container"><p class="label">Website design · Niagara &amp; GTA</p><h1>Give people a clear<br>reason to choose you.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Give customers the information and confidence they need to get in touch. Bring strategy, copy, design, and current web technology together in a site built around your business. Start with a free private preview before committing.</p><div class="hero-actions">''' + cta('Request a free preview', 'Web development') + '''<a class="text-link" href="#plans">Compare packages ↗</a></div></div><figure class="website-hero-art"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" fetchpriority="high" alt="The website built for musician Frank Baggetta."></figure></div></section>
<section class="capabilities container section"><h2>Answer their questions.<br>Make the next step easy.</h2><div class="capability-list"><article><h3>Make your services clear</h3><p>Help visitors decide whether you’re right for them. Clear service descriptions, answers to common questions, and examples of your work give them something specific to judge.</p></article><article><h3>Turn interest into an enquiry</h3><p>A clear phone link, quote form, or connection to your booking system gives visitors somewhere to go next. We check those paths on mobile as well as desktop.</p></article><article><h3>Build in the foundations</h3><p>Give customers a site they can use on a phone, with readable pages and clear ways to contact you. Hosting and support are included as agreed in your package or project scope.</p></article></div><p class="section-intro">Based in Welland, serving Niagara and the GTA. <a class="text-link" href="/website-design-niagara/">Website design in Niagara &rarr;</a> · <a class="text-link" href="/website-design-welland/">Website design in Welland &rarr;</a> · <a class="text-link" href="/website-design-st-catharines/">Website design in St. Catharines &rarr;</a></p></section>''' + pricing() + '''<section class="approach-section container section"><h2>See your website<br>before you commit.</h2><ol class="process-list"><li><h3>Tell me what customers need.</h3><p>Share your current site or social page, your services, and what visitors should be able to do.</p></li><li><h3>Review your free preview.</h3><p>I prepare a private preview so you can judge the copy and design direction. There’s no obligation to buy.</p></li><li><h3>Agree on the build.</h3><p>We confirm the pages, functionality, price, and ongoing support before paid work begins. You review the finished site before it goes live.</p></li></ol></section>''' + project() + faq([
('Do I need to write the copy?', 'I write the website copy using the information and examples you share. You review it for accuracy and tone before publication.'),
('Can you work with my existing website?', 'Yes, where the platform and access support the changes. We look at what you have before deciding whether to update or rebuild.'),
('Can I keep my booking system?', 'Where supported, we can link to or embed your existing booking flow. We check that connection before including it in the scope.'),
('Do you offer one-time website builds?', 'Yes. One-time builds are also available. We agree the pages, content, functionality, and price before paid work begins.')
]) + contact('See what your<br>website could become.', 'Share your current website or tell me what you’re starting. I’ll prepare a free private preview so you can see a direction before deciding.', label='Request a free preview', service='Web development')

growth = '''<section class="service-hero container"><p class="label">SEO &amp; content marketing · Niagara &amp; GTA</p><h1>Get found for the work<br>you want more of.</h1><div class="hero-lower growth-lower"><div class="hero-copy"><p class="hero-description">Give the right customers more ways to find you and more reasons to get in touch. Put a decade of marketing experience behind your search, content, and campaigns, with a strategy shaped by your business and refined using performance data.</p><div class="hero-actions">''' + cta('Request a free website preview', 'Growth marketing') + ' ' + cta('Discuss your marketing', 'Growth marketing') + '''</div></div>''' + local.JOURNEY + '''</div></section>
<section class="capabilities container section"><h2>Be useful at each step<br>of the customer’s search.</h2><div class="capability-list"><article><h3>Show what you do and where</h3><p>Make your services and location clear wherever customers look. Your service pages, Google Business Profile, and listings are reviewed together, including technical issues that could keep pages out of search.</p></article><article><h3>Answer what customers ask</h3><p>Give customers useful answers drawn from your experience. Get service pages, articles, social posts, and emails written around an agreed strategy, with each draft approved by you or Matt before it goes out.</p></article><article><h3>See what brings interest</h3><p>See which pages people find, click, and enquire through, using the data available. Search results and mentions in ChatGPT and Claude help guide what to improve next.</p></article></div><p class="section-intro">Working with businesses across Niagara and the GTA. <a class="text-link" href="/niagara-seo/">Explore local SEO in Niagara &rarr;</a></p></section>
<section class="approach-section container section"><h2>Start with the customers<br>you want to reach.</h2><ol class="process-list"><li><h3>Choose the priority.</h3><p>Tell me which services you want to promote and where your customers are. We review your current site and available search data to find a useful starting point.</p></li><li><h3>Put the work in motion.</h3><p>We agree on the pages, content, channels, and measures. Start with a defined search or content project, or choose a package for ongoing work.</p></li><li><h3>Review and adjust.</h3><p>We look at what people found, clicked, and enquired about, where that data is available. Those observations guide the next round of work.</p></li></ol></section>
<section class="case-story container section"><p class="label">Website &amp; local search · Frank Baggetta</p><h2>Help people find<br>the service they need.</h2><p>Frank Baggetta’s rebuilt website gave each of his five music services its own page, with performance videos and a direct route to enquire. Frank reported three new enquiries in the first month after the original launch.</p><p><a class="text-link" href="/frank-baggetta/">Read Frank’s case study ↗</a></p></section><section class="case-story container section"><p class="label">Selected marketing work</p><h2>See the work<br>behind the experience.</h2><p>Explore selected results and deliverables from Matt’s earlier content work in the <a href="https://www.jettagrove.com/#results" target="_blank" rel="noopener">Jetta Grove portfolio</a>:</p><ul class="case-results"><li><strong>SeamlessFi social content:</strong> average views per post rose from 1,412 to 3,871 between April and November 2025, while monthly posting volume fell from 38 to 20.</li><li><strong>io.net organic search:</strong> estimated monthly organic visits across the full domain grew from 5,097 to 27,022. These are traffic estimates, separate from the portfolio’s blog-only figures.</li><li><strong>Nulogy and Top Hat:</strong> sales decks, campaign materials, and product videos, with work samples you can inspect.</li></ul>''' + local.RESULTS_GROWTH + '''<p class="small-note">These examples come from Matt’s earlier content and marketing work. The portfolio reports the results and links to selected deliverables.</p></section>''' + pricing() + founder() + faq([
('Do I need a new website first?', 'Not necessarily. We can improve an existing site where its platform and access support the agreed work.'),
('Can you guarantee rankings or AI recommendations?', 'No. Google, ChatGPT, and Claude choose their own results. We agree the work and measures without promising rankings, citations, or sales.'),
('Can we start with a specific project?', 'Yes. A defined search or content project can be scoped separately from the monthly packages.')
]) + contact('Which services would<br>you like more enquiries for?', 'Tell me what you want to promote, where your customers are, and what marketing you already have. We’ll identify a practical place to start.', label='Discuss your marketing', service='Growth marketing')

automation = '''<section class="service-hero container"><p class="label">AI automation · Niagara &amp; GTA</p><h1>Get the recurring work<br>off your list.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Spend less time preparing research, drafting follow-ups, and updating records. Get AI workflows built around your business, with clear points for review.</p>''' + cta('Talk through a task', 'AI automation') + '''</div><div class="automation-picker"><p class="picker-heading" id="picker-heading">I need a hand with…</p><div class="picker-choices" role="group" aria-labelledby="picker-heading"><button type="button" data-automation-choice="research" aria-pressed="true" aria-controls="automation-research">Research</button><button type="button" data-automation-choice="content" aria-pressed="false" aria-controls="automation-content">Content drafts</button><button type="button" data-automation-choice="data" aria-pressed="false" aria-controls="automation-data">Data &amp; records</button></div><div class="picker-result" aria-live="polite" aria-atomic="true"><div id="automation-research" data-automation-panel="research"><p class="label">Illustrative example</p><h2>A brief, ready to use.</h2><p>Relevant prospects or market updates, with source links and questions worth a closer look.</p></div><div id="automation-content" data-automation-panel="content" hidden><p class="label">Illustrative example</p><h2>Drafts ready for approval.</h2><p>Emails and social posts based on your strategy. You or Matt approve each draft before it goes out.</p></div><div id="automation-data" data-automation-panel="data" hidden><p class="label">Illustrative example</p><h2>Records ready to update.</h2><p>Details pulled from supported files, checked for gaps and duplicates, and prepared for your spreadsheet or business app.</p></div></div></div></div></section>
<section class="builds-section automation-example container section" id="builds"><p class="label">Project example · Interview research and updates</p><h2>Keep the project moving<br>between calls.</h2><p class="section-intro">For a website refresh, Matt built an AI-assisted workflow for interview prep and project updates, with a searchable hub to review the work.</p><div class="builds"><article><h3>Before the call</h3><p>An agenda built from project sources and open questions.</p></article><article><h3>After the call</h3><p>New answers carried into the briefs, questions, and drafts they affect.</p></article><article><h3>In the hub</h3><p>Sources and working documents brought together in a rebuilt, searchable view.</p></article></div></section>
<section class="approach-section container section"><h2>Start with one task.<br>Build from there.</h2><ol class="process-list"><li><h3>Walk through the work.</h3><p>Start with a free conversation, then an interview with the person who knows the process.</p></li><li><h3>Agree the strategy.</h3><p>Confirm the workflow, access, review points, and costs before paid work begins.</p></li><li><h3>Build and test.</h3><p>Try real examples and exceptions. Review how it works before putting it to use.</p></li><li><h3>Refine and expand.</h3><p>Improve the workflow or add another task, with further work scoped together.</p></li></ol></section>
<section class="container section"><h2>AI workflow automation.<br>One process at a time.</h2><p class="section-intro">AI workflow automation is the name for connecting recurring research, drafts, and record updates to the tools you already use, with review points agreed before anything runs on its own. Start with one process in Niagara or the GTA, then refine and expand.</p></section>''' + faq([
('What kinds of work can you automate?', 'The work that keeps coming back: research briefs, content drafts for approval, and data or record updates. We map the process in an interview, agree the review points, then build and test before you rely on it.'),
('What is AI automation?', 'AI workflows that use your information and connected software to carry out recurring business tasks, with agreed steps and review points.'),
('Do we need documented procedures?', 'No. An interview with the person who knows the work is enough to map the process, including exceptions.'),
('Will it work with our existing tools?', 'We check which connections your tools support before agreeing the build. Sometimes a feature you already have is enough.'),
('Who approves customer-facing work?', 'You or Matt approve each email or social draft before it is sent or published. The strategy and review points are agreed first.'),
('What will it cost?', 'Each workflow is quoted around the process, tools, and frequency. You agree the build, software, and support costs before paid work starts.')
]) + contact('Which task would you<br>like to stop repeating?', 'Bring one recurring task and the tools you use. Start with a free conversation.', label='Talk through a task', service='AI automation')

website_design_niagara = '''<section class="service-hero container"><p class="label">Website design · Niagara Region</p><h1>A website that shows<br>what you do and where.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Help Niagara customers see what you offer, where you work, and why you’re a good fit. Get a website that brings your services and work examples together, with a clear way to enquire.</p><div class="hero-actions">''' + cta('Request a free preview', 'Web development') + '''<a class="text-link" href="/services/websites/#plans">Compare packages &rarr;</a></div></div><figure class="website-hero-art"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" fetchpriority="high" alt="The website built for Toronto musician Frank Baggetta."></figure></div></section>
<section class="capabilities container section has-map"><h2>Make it clear<br>you serve their area.</h2><div class="capability-list"><article><h3>Explain where you work</h3><p>Give visitors clear service-area information, location details, and a way to check whether you can help. I build that into the page structure and copy.</p></article><article><h3>Make your services easy to find</h3><p>Descriptive page titles, readable service pages, and connections to your Google Business Profile help people understand what you offer and where to reach you.</p></article><article><h3>Give them a next step</h3><p>Visitors can call, request a quote, or reach your booking system through the connections we agree on. The layout is checked on mobile and desktop.</p></article></div><p class="section-intro">I’m based in Welland and work with businesses in St. Catharines, Niagara Falls, and across Niagara. <a class="text-link" href="/website-design-welland/">Website design in Welland &rarr;</a> · <a class="text-link" href="/website-design-st-catharines/">Website design in St. Catharines &rarr;</a></p>''' + local.canal_map('welland', also=('welland', 'stcatharines', 'niagarafalls')) + '''</section>''' + pricing() + project() + faq([
('Who will build my website?', 'You work directly with me, Matthew Baggetta, from the first conversation through the copy, design, and launch. I’m based in Welland.'),
('Can you help with an existing website?', 'Yes, where the platform and access support the changes. We review what you have before deciding whether to update or rebuild.'),
('What if I need more than a website?', 'The monthly packages include ongoing search, content, and marketing support. Custom AI automation is scoped separately. We agree the work before paid work begins.'),
('Do you work with businesses outside Niagara?', 'Yes. I also work with businesses across the GTA and Ontario.')
]) + contact('Show customers<br>where you can help.', 'Tell me what your business does and which parts of Niagara you serve. I’ll prepare a free private website preview for you to review.', label='Request a free preview', service='Web development')

website_design_welland = '''<section class="service-hero container"><p class="label">Website design · Welland, Ontario</p><h1>Your business in Welland.<br>A website that explains it.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Give customers the information they need before they call: your services, examples of your work, and how to get started. Get the copy, design, and build taken care of by a website specialist based here in Welland.</p><div class="hero-actions">''' + cta('Request a free preview', 'Web development') + '''<a class="text-link" href="/services/websites/#plans">Compare packages &rarr;</a></div></div><figure class="website-hero-art"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" fetchpriority="high" alt="The website built for Toronto musician Frank Baggetta."></figure></div></section>
<section class="capabilities container section has-map"><h2>Turn what you know<br>into a site customers can use.</h2><div class="capability-list"><article><h3>Copy that explains the work</h3><p>You bring the business knowledge. I turn it into service descriptions, answers to common questions, and clear next steps. You review the copy before it goes live.</p></article><article><h3>A useful site on a phone</h3><p>Customers should be able to read about your services and contact you without wrestling with the page. I check the mobile layout, phone links, and enquiry path.</p></article><article><h3>Clear local information</h3><p>Your service area, location details, and Google Business Profile connections belong alongside the work you do. I include those foundations in the site we agree to build.</p></article></div>''' + local.canal_map('welland') + '''</section>''' + pricing() + '''<section class="approach-section container section"><h2>Work with the person<br>building your website.</h2><div><p>I’m based in Welland, and you work directly with me throughout the project. Share what you have, whether that’s an existing site, a social page, or a description of the business.</p><p>I’ll prepare a free private preview. If the direction feels right, we’ll agree on the build and support before paid work starts.</p>''' + cta('Request a free preview', 'Web development') + '''</div></section>''' + project() + contact('Let’s put your business<br>into words and pages.', 'Share your current website or tell me what you’re starting in Welland. Your first step is a free private preview, with no obligation to buy.', label='Request a free preview', service='Web development')

website_design_st_catharines = '''<section class="service-hero container"><p class="label">Website design · St. Catharines, Ontario</p><h1>Website design for<br>St. Catharines businesses.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Make it easy for someone comparing businesses to choose yours. Get a website that explains your services, shows your work, and gives visitors a clear way to call or enquire, with the copy, design, and build handled for you.</p><div class="hero-actions">''' + cta('Request a free preview', 'Web development') + '''<a class="text-link" href="/services/websites/#plans">Compare packages &rarr;</a></div></div><figure class="website-hero-art"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" fetchpriority="high" alt="The website built for Toronto musician Frank Baggetta."></figure></div></section>
<section class="capabilities container section has-map"><h2>Give visitors enough<br>to take the next step.</h2><div class="capability-list"><article><h3>Explain the fit</h3><p>Clear service descriptions and relevant work examples help visitors decide whether you’re right for them. I write the copy around what your customers need to know.</p></article><article><h3>Make enquiries straightforward</h3><p>Put a useful next step beside the service: a phone link, quote form, or connection to your booking system. We agree the connections and check them on mobile and desktop.</p></article><article><h3>Support local discovery</h3><p>Readable pages, descriptive titles, service-area details, and Google Business Profile connections make your business information easier to find and understand.</p></article></div>''' + local.canal_map('stcatharines') + '''</section>''' + pricing() + '''<section class="approach-section container section"><h2>A clear direction<br>before you commit.</h2><div><p>You work directly with me, Matthew Baggetta, from the first conversation to launch. I’m based in Welland and serve businesses in St. Catharines and across Niagara.</p><p>Send your current site or social page and tell me what you want to improve. I’ll prepare a free private preview so you can review the direction before agreeing to a build.</p>''' + cta('Request a free preview', 'Web development') + '''</div></section>''' + project() + contact('Make your next enquiry<br>easier to start.', 'Tell me about your St. Catharines business and what customers should be able to do on your site. I’ll prepare a free private preview.', label='Request a free preview', service='Web development')

niagara_seo = '''<section class="service-hero container"><p class="label">Niagara SEO · Local search</p><h1>Help local customers<br>find the work you do.</h1><div class="hero-lower"><div class="hero-copy"><p class="hero-description">Help people searching in Niagara find the services you offer. Get your website, Google Business Profile, and content working from the same clear information about what you do and where you serve customers.</p><div class="hero-actions">''' + cta('Request a free website preview', 'Growth marketing') + ' ' + cta('Discuss your local SEO', 'Growth marketing') + '''</div></div>''' + local.JOURNEY + '''</div></section>
<section class="capabilities container section"><h2>Connect your services<br>to the searches that matter.</h2><div class="capability-list"><article><h3>Check what can be found</h3><p>I review whether search engines can reach and index your pages, alongside your Google Business Profile and local business details.</p></article><article><h3>Give each service an answer</h3><p>Useful service pages explain the work, answer customer questions, and give readers a direct way to enquire. Clear headings and links help people navigate the information.</p></article><article><h3>Focus on where you work</h3><p>We match the content to your actual service area, whether that’s Welland, St. Catharines, Niagara Falls, or the wider region. Available search and enquiry data helps us choose what to work on next.</p></article></div></section>
<section class="case-story container section"><p class="label">Website &amp; local search · Frank Baggetta · Toronto</p><h2>A clearer site.<br>Three first-month enquiries.</h2><p>Frank said his old website had never brought him a booking in fifteen years. The rebuild brought his five music services, performance videos, and enquiry paths together. He reported three new enquiries in the first month after the original launch.</p><p><a class="text-link" href="/frank-baggetta/">Read Frank’s case study &rarr;</a></p></section>''' + pricing() + faq([
('Do you guarantee rankings?', 'No. Rankings depend on the site, competition, demand, and decisions made by search engines. We agree the work and how progress will be assessed.'),
('How long does local SEO take?', 'The timeline depends on your site and the work we agree on. Completing a page or technical fix does not mean search results change immediately. We set a work schedule and review the available search data over time.'),
('Can you work on SEO without rebuilding my website?', 'Yes, where the platform and access support the changes. We review the current site before deciding what needs to change.'),
('Can I start with a specific SEO project?', 'Yes. Standalone search work is scoped separately from the monthly website and growth packages.'),
("How much does Niagara SEO cost?", "Three monthly packages (CAD): Launch ($199/month plus $750 setup), Grow ($699/month plus $1,500 onboarding), and Dominate ($1,299/month plus $2,500 onboarding). Each includes local SEO and content work at that tier. Request a free website preview, or get in touch, and we'll match the package to your business.")
]) + contact('What should customers<br>be finding you for?', 'Share your website, the services you want to promote, and where you work in Niagara. We’ll discuss the search work that fits your business.', label='Discuss your local SEO', service='Growth marketing')

frank_case = '''<section class="service-hero container case-hero"><p class="label">Case study · Frank Baggetta · Toronto</p><h1>Help more customers<br>find you and get in touch.</h1><p class="hero-description">You want people to find your business, see why you’re a good fit, and get in touch. Whether you’re starting from scratch or replacing a website that isn’t bringing in work, that’s what we build around. For Frank, the new site started bringing in enquiries in its first month.</p><div class="hero-actions"><a class="button" href="https://frankbaggetta.ca/" target="_blank" rel="noopener">Visit Frank’s website <span aria-hidden="true">↗</span></a><a class="text-link" href="/#work">More websites ↗</a></div></section>
<figure class="container case-screenshot"><a href="https://frankbaggetta.ca/" target="_blank" rel="noopener"><img src="/assets/frankbaggetta-20260908.webp" width="1440" height="1000" alt="Frank Baggetta’s updated website, headed The Accordion Player Who Gets Toronto Dancing." fetchpriority="high"></a><figcaption>Frank’s current website, captured September 8, 2026.</figcaption></figure>
<article class="case-story container section"><h2>A long career.<br>A website that wasn’t bringing bookings.</h2><p>Frank Baggetta has performed for fifty years, including at the Rogers Centre and the Royal Ontario Museum. He said the website he’d had for fifteen years had never brought him a booking.</p><p>The old site needed a clearer structure, a usable mobile layout, and a cleanup of dead pages. Visitors needed a way to find the music for their event and contact Frank.</p><h2>A clearer way to find the right music</h2><p>The rebuild organized the site around five services: weddings, corporate events, cocktail piano, Italian music, and jazz. Each service had its own page, with copy and structure written for local search.</p><p>Performance videos let visitors hear Frank’s music. The mobile layout and direct enquiry paths made it easier to go from browsing a service to asking about an event.</p>
<h2>Refining the site as the work continues</h2><p>The current site brings weddings, corporate and private events, and performance videos into the main navigation. Visitors can explore Frank’s music, experience, and repertoire before asking about a date.</p><p>The enquiry form now asks for the event date, venue, guest count, performance length, and type of music. It explains what Frank will review and that he replies personally. Those details give him more context for the conversation.</p><h2>More traffic.<br>Real enquiries.</h2><div class="case-stats"><div class="stat-rise"><strong>Nearly 3×</strong><span>The organic traffic from Google, month over month</span>''' + local.RESULTS_FRANK + '''</div><div><strong>First month</strong><span>The new website started bringing in enquiries, reported by Frank</span></div></div><p class="small-note">Google traffic measured by search clicks, August 23–September 19, 2026, compared with the preceding 28 days. Updated September 21, 2026.</p>
<blockquote class="case-quote"><p>“I had a website for fifteen years and it never brought me a single booking. I’m not a tech person, so I kept putting it off. Matt had my new site live faster than I thought was possible, and in the first month it already brought in three new enquiries. I sent him what I had and he handled the rest. Completely painless.”</p><cite>Frank Baggetta · FrankBaggetta.ca</cite></blockquote></article>''' + contact('Give your own work<br>a clearer place online.', 'Share your website and the services you want to promote. I’ll prepare a free private preview so you can see a direction for your business.', label='Request a free preview', service='Web development')

evelyns_concept = '''<section class="service-hero container case-hero"><p class="label">Concept build · Evelyn's Sandwich Factory · Welland</p><div class="concept-banner"><p>Real Welland business. Concept website – not a commissioned client project.</p></div><h1>A clear menu.<br>A clear way to order.</h1><p class="hero-description">I built this concept to show how a local sandwich shop can put menu, ordering, and story on a fast, mobile-first site.</p><div class="hero-actions"><a class="button" href="https://immeasurablematt.github.io/evelyns-sandwich-factory/" target="_blank" rel="noopener">View the live concept <span aria-hidden="true">↗</span></a><a class="text-link" href="/#work">More websites ↗</a></div></section>
<article class="case-story container section"><h2>What this concept shows</h2><ul class="case-results"><li>A readable menu people can scan on a phone.</li><li>A direct path to call or place an order.</li><li>A short owner story without burying the next step.</li></ul><p class="small-note">Evelyn's Sandwich Factory is a real local business. This website is a concept build I made to show the work – not a commissioned client project, and not a Well and Good Growth case study.</p></article>''' + contact('Could your website<br>be doing more for you?', 'Tell me about your business and request a free private website preview.', label='Request a website preview', service='Web development')

jk_motors_concept = '''<section class="service-hero container case-hero"><p class="label">Concept build · JK Motors · Welland</p><div class="concept-banner"><p>Real Welland business. Concept website – not a commissioned client project.</p></div><h1>Call first.<br>Know what the shop does.</h1><p class="hero-description">I built this concept to show how a local auto shop can lead with a phone call, list services clearly, and keep the next step obvious.</p><div class="hero-actions"><a class="button" href="https://immeasurablematt.github.io/jk-motors/" target="_blank" rel="noopener">View the live concept <span aria-hidden="true">↗</span></a><a class="text-link" href="/#work">More websites ↗</a></div></section>
<article class="case-story container section"><h2>What this concept shows</h2><ul class="case-results"><li>A call-first layout for repair enquiries.</li><li>Plain service pages that explain the work.</li><li>A simple path from symptom to call to diagnosis framing.</li></ul><p class="small-note">JK Motors is a real local business. This website is a concept build I made to show the work – not a commissioned client project, and not a Well and Good Growth case study.</p></article>''' + contact('Could your website<br>be doing more for you?', 'Tell me about your business and request a free private website preview.', label='Request a website preview', service='Web development')

pages = {
    'frank-baggetta/index.html': page('Frank Baggetta website case study', 'See how Frank Baggetta’s website rebuild helped bring in enquiries, with nearly three times the organic traffic from Google, month over month.', frank_case, 'websites'),
    'work/evelyns/index.html': page("Evelyn's Sandwich Factory concept", 'A concept website I built to show how a local sandwich shop can put menu, ordering, and story on a fast, mobile-first site.', evelyns_concept, 'websites'),
    'work/jk-motors/index.html': page('JK Motors concept', 'A concept website I built to show how a local auto shop can lead with a phone call, list services clearly, and keep the next step obvious.', jk_motors_concept, 'websites'),
    'index.html': page('AI automation, websites and growth marketing', 'Get recurring work off your plate with AI automation, plus websites and marketing that help customers find and choose your business. Niagara and the GTA.', home),
    'services/websites/index.html': page('Website design in Niagara & the GTA', 'Website strategy, copy, design, and development with Matthew Baggetta in Welland. Compare packages or request a free private website preview.', websites,'websites'),
    'services/growth/index.html': page('Niagara SEO & content marketing', 'Local SEO and content marketing for Niagara and GTA businesses. Improve your pages and listings, and review visibility in Google, ChatGPT, and Claude.', growth,'growth'),
    'services/automation/index.html': page('Custom AI automation in Niagara & the GTA', 'AI workflows for recurring research, marketing drafts, data, and project tasks. Start with one process, agree the review points, then refine and expand.', automation,'automation'),
    'website-design-niagara/index.html': page('Website design in Niagara', 'Website design for Niagara businesses, with clear services, local information, and a direct route to enquire. Work with Matt and request a free preview.', website_design_niagara, 'websites'),
    'website-design-welland/index.html': page('Website design in Welland', 'Website copy, design, and development with Matt in Welland. Show customers what you do and how to get started. Request a free private preview.', website_design_welland, 'websites'),
    'website-design-st-catharines/index.html': page('Website design in St. Catharines', 'Website design for St. Catharines businesses. Clear services, work examples, and a direct way to enquire. Work with Matt in Welland. Free preview available.', website_design_st_catharines, 'websites'),
    'niagara-seo/index.html': page('Niagara SEO services', 'Local SEO for Niagara businesses. Service pages, Google Business Profile, and content built around what you do and where you work. Discuss your site with Matt.', niagara_seo, 'growth'),
}

# Preserve the existing privacy content while using the approved site shell.
privacy_body = (ROOT / 'content/privacy.html').read_text()
privacy_body = privacy_body.replace('Well and Good is operated', 'Well and Good Growth is operated')
privacy_body = privacy_body.replace('class="page-hero"', 'class="service-hero container"').replace('class="section section-paper"', 'class="case-story container section"')
privacy_body = re.sub(r' data-reveal', '', privacy_body)
privacy_body = re.sub(r'<p class="breadcrumbs">.*?</p>', '', privacy_body, flags=re.S)
privacy_body = privacy_body.replace('class="eyebrow"', 'class="label"').replace('<p>Well and Good Growth is operated', '<p class="hero-description">Well and Good Growth is operated')
pages['privacy/index.html'] = page('Privacy notice', 'How Well and Good Growth handles the information you submit through this website.', privacy_body)
pages['contact/index.html'] = page('Contact Matthew Baggetta', 'Discuss a website, growth marketing, or custom AI automation with Matthew Baggetta.', '<section class="service-hero container"><p class="label">Contact Matt</p><h1>Tell me what you’d<br>like to work on.</h1><p class="hero-description">A new website, a service you want to promote, or a task you’re tired of repeating. I’ll reply personally, and I can send a free website preview so you see the direction before you decide.</p></section><section class="container section contact-page"><!-- CONTACT_FORM --></section>')
contact_html = pages['contact/index.html']
inline_form = re.search(r'<dialog.*?>(.*?)</dialog>', contact_html, re.S).group(1)
inline_form = inline_form.replace('<button class="dialog-close" type="button">Close</button>', '')
contact_html = re.sub(r'<dialog.*?</dialog>', '', contact_html, flags=re.S)
pages['contact/index.html'] = contact_html.replace('<!-- CONTACT_FORM -->', '<div class="contact-panel">' + inline_form + '</div>')
pages['thank-you/index.html'] = page('Thank you', 'Thank you for contacting Well and Good Growth.', '<section class="service-hero container"><h1>Thanks for getting in touch.</h1><p class="hero-description">I’ll review what you’ve shared and reply personally by email. If you’ve asked for a conversation, we’ll arrange a time together.</p><a class="button" href="/">Back to home <span aria-hidden="true">↗</span></a></section>')
pages['404.html'] = page('Page not found', 'Find websites, growth marketing, and AI automation services from Well and Good Growth.', '<section class="service-hero container"><h1>Page not found.</h1><p class="hero-description">The page you’re looking for may have moved. Explore websites, growth marketing, or AI automation from the menu, or head back to the homepage.</p><a class="button" href="/">Back to home <span aria-hidden="true">↗</span></a></section>')


def build():
    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir()
    for name in ['assets', 'fonts']:
        shutil.copytree(DESIGN / name, OUTPUT / name)
    for name, versioned_name in ASSETS.items():
        (OUTPUT / versioned_name).write_text(BUNDLES[name])
    urls = []
    for name, html in pages.items():
        route = '/' + name.removesuffix('index.html')
        url = 'https://www.wellandgoodgrowth.ca' + route
        title = re.search(r'<title>(.*?)</title>', html).group(1)
        description = re.search(r'<meta name="description" content="([^"]*)">', html).group(1)
        metadata = f'<link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:site_name" content="Well and Good Growth"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="{url}"><meta property="og:image" content="{SOCIAL_IMAGE}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Well and Good Growth"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="{SOCIAL_IMAGE}"><meta name="twitter:image:alt" content="Well and Good Growth">'
        schema = {'@context':'https://schema.org', '@type':'ProfessionalService', 'name':'Well and Good Growth', 'url':'https://www.wellandgoodgrowth.ca/', 'email':'matt@wellandgoodwebsites.ca', 'founder':{'@type':'Person','name':'Matthew Baggetta'}, 'areaServed':['Niagara Region, Ontario','Greater Toronto Area, Ontario']}
        metadata += '<script type="application/ld+json">' + json.dumps(schema) + '</script><script>window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)};</script><script defer src="/_vercel/insights/script.js"></script>'
        html = html.replace('</head>', metadata + '</head>')
        if name in {'thank-you/index.html', '404.html'}:
            html = html.replace('index,follow', 'noindex,follow')
        else:
            urls.append(url)
        path = OUTPUT / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html.replace('<br>', '<br> '))
    (OUTPUT / 'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://www.wellandgoodgrowth.ca/sitemap.xml\n')
    (OUTPUT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + ''.join(f'<url><loc>{url}</loc></url>' for url in urls) + '</urlset>')
    (OUTPUT / 'llms.txt').write_text('# Well and Good Growth\n\nWebsites, growth marketing, and custom AI automation with Matthew Baggetta in Welland, Ontario. AI automation is bespoke. Website and growth packages are listed on their service pages. Frank Baggetta is a completed client website. Evelyn’s and JK Motors are concept builds.\n\n' + '\n'.join('- ' + url for url in urls) + '\n')
    print(f'Built approved Growth site: {len(pages)} pages in {OUTPUT}')


if __name__ == '__main__':
    build()
